version: 2

models:
  - name: dim_listing_cleansed
    description: "A starter dbt model"
    columns:
      - name: listing_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fct_reviews
    description: "Fact table for reviews"
    columns:
      - name: review_date
        tests:
          - not_null
    tests:
      - custom:
          name: consistent_created_at
          description: "Ensure no review date is before its listing was created"
          file: tests/consistent_created_at.sql